### ISSUE TITLE
Getting 'WeakMap.prototype.set: 'key' is not an object' Error

### ISSUE THREAD

**Issue by mshahrouri** [Microsoft/IEDiagnosticsAdapter#12]
Using x64 version gives "connection rejected" error as in issue #9 by @praveenpuglia so as suggested I've tried to use the x86 version in the adapter window I got *"Client connection accepted for: /devtools/page/3AD29AEA-47B1-4573-BA76-AF85394FA44D as :000409BC"*
but then i get **"An unhandled exception ('WeakMap.prototype.set: 'key' is not an object') occured in iexplore.exe"**

Environment:
- windows 8.1 x64
- ie version 11.0.9600.17690
- chrome version 42.0.2311 beta-m (64-bit)

P.S.: the page I'm trying to open in ie is hosted in a local server within my network

**Comment by praveenpuglia** [comment]
Did you try what @alexcope suggested? I had them unchecked so may be the x86 worked instantly without any errors. Software and OS versions are same as yours.

>Under Internet options/advanced in Internet Explorer, ensure both "enable enhanced protective mode", >and "enable 64 bit tabs for enhanced protective mode" are not checked.

**Comment by mshahrouri** [comment]
@praveenpuglia I've already tried that with no luck

**Comment by praveenpuglia** [comment]
It looks like a webpage specific issue rather than the adapter itself. That's the error you get when you use anything other than object as key as first param of `WeakMap.prototype.set` in IE.

Tried this to confirm
<pre>
    var wm = new WeakMap();
    wm.set("123",12);
</pre>

Can you try a different web page and see if the issue persists?

**Comment by mshahrouri** [comment]
Ok it works for other pages, thanks @praveenpuglia

**Comment by praveenpuglia** [comment]
Nice! Please mark it as closed. I can't do that yet.

**Comment by thvd** [comment]
Looks like the same bug as described here; https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12112572/
