### ISSUE TITLE
Ability to use this adapter without a server

### ISSUE THREAD

**Issue by bedney** [Microsoft/IEDiagnosticsAdapter#14]
Chrome allows you to use its debugging protocol from a plugin without a server by writing an extension:

https://developer.chrome.com/extensions/debugger

It would be very nice to be able to do this using this adapter as well.

**Comment by danmosemsft** [comment]
@bedney, can you clarify, do you mean, you'd like to be able to write an extension for IE that could work against IE using the protocol?

**Comment by bedney** [comment]
@danmosemsft - Thanks for the quick reply.

Yes. On Chrome, we leverage this capability by loading a Chrome extension into Chrome and speak the debugging protocol directly to a Chrome task with no server involved. The wireline protocol is the same, but you attach directly to the target. The API is detailed on that page I linked to above.

**Comment by andysterland** [comment]
We don't have plans to extend this to IE extensions yet or enabling extensions of F12. 

That being said we are keen for the F12 tools to have a HTML/JS extension model that is highly interoperable with Chrome. No plans yet though and we're going to wait for the Project Spartan extensibility model plans before plans for F12 can be made.

**Comment by bedney** [comment]
@andysterland - Thanks for the reply! I can't tell you how cool it is to see Microsoft people on GitHub, collaborating with their developer community! :-)

I understand the desire to wait and see how Spartan might change the extensibility model. If you guys could keep a capability like this in mind when that shakes out, that'd be great. Thanks!
