### ISSUE TITLE
Is there a plan to support OSX platform?

### ISSUE THREAD

**Issue by leecade** [Microsoft/IEDiagnosticsAdapter#16]

**Comment by andysterland** [comment]
No plans.

The adapter itself connects to IE locally only so has to be on the same machine as IE. Which is Windows only. 

That doesn't mean to say that clients of the adapter need to be local always.

**Comment by danmosemsft** [comment]
Let us know if you get the Chrome tools on OSX connecting to IE (on Windows). Can't think of why it should not work, assuming you can debug Chrome on that same Windows machine (proving the firewall is open)

**Comment by praveenpuglia** [comment]
should this be closed now?
