### ISSUE TITLE
Any plans to show the applied styles on elements?

### ISSUE THREAD

**Issue by praveenpuglia** [Microsoft/IEDiagnosticsAdapter#18]
Is there any plan to show the styles applied for elements? probably even add the capability of modifying them and test? I am not sure if Chrome Debugger can allow that.
![styles](https://cloud.githubusercontent.com/assets/313363/7351309/0912bf16-ed22-11e4-8fb8-13795cc7c4f4.PNG)

**Comment by danmosemsft** [comment]
Our goal is to make everything work in the DOM explorer, Console, and Debugger that both the Chrome tools and the IE tools support. So that would include the Styles pane. Expect progress this week.

Long term, we'd like to get some of the other tools working, but that's where some of the semantics diverge so it remains to be seen.

**Comment by praveenpuglia** [comment]
I have been looking into the debugger API. I want to contribute but can't figure out where to start. :(

**Comment by alexcope** [comment]
What are you interested in in doing? I'd be happy to explain what I know and help you get started.

**Comment by praveenpuglia** [comment]
I don't know how the requests are made and responses are parsed for use. Basically I don't know how this works. I can help with HTML, CSS and JS though!

**Comment by alexcope** [comment]
The chrome debugging protocol is documented here: https://developer.chrome.com/devtools/docs/protocol/1.1/index 
The short version of how the IEDiagnosticsAdaptor works is we get a command over a web socket from the chrome dev tools, (or any other piece of software that communicates via the chrome debugging protocol). We then have JavaScript running on the page (the IEWebKitImpl project) that receives the command, does appropriate things, and then sends a response back.
To get the styles pane working, I’m guessing that we need to implement DOM.getAttributes
The Basic workflow that I’m using is as follows

1. Debug the chrome dev tools to see how the Chrome dev tools respond to a command.**
2. Implement a handler in JavaScript that is injected onto the page. In this case add a function GetAttributes in Dom.ts that gets the node specified using DOMHandler::_mapUidToNode and reads the relevant properties from the node
3. Format a response that mimics the response chrome gives as closely as possible. Set this on the processedResult object, and then browserHandler.postResponse will send it back to the chrome dev tools.

Hopefully this it helpful for getting you started!

** To debug the chrome dev tools with the chrome dev tools, follow these steps
1. Launch chrome from the command prompt with the flag "--remote-debugging-port=9222". For example run “C:\Program Files (x86)\Google\Chrome\Application>chrome --remote-debugging-port=9222”
2. Navigate to a website
3. Open another chrome tab, and navigate to localhost:9222, select the site you navigated to in step 2
4. Hit f12 to debug the chrome dev tools with the chrome dev tools.
5. Under the network inspector, you should see a line that looks like a GUID. Select this to see all of the commands that the dev tools are sending to the page and all of the responses. You may need to refresh the dev tools that are pointed at the page to see network traffic

**Comment by praveenpuglia** [comment]
Awesome! that helps a lot. I'll be looking into it and play around. Thanks! 
Next thing to do - understand TS.

**Comment by praveenpuglia** [comment]
I'll close this as the discussion will be off topic. Do we have any irc channel or any other channel to talk to each other? I have setup the project locally and confused about a couple of stuff. would appreciate some help.
