### ISSUE TITLE
[BUILD] asio listen error : 10048 : only one usage of each socket is normally permitted.

### ISSUE THREAD

**Issue by praveenpuglia** [Microsoft/IEDiagnosticsAdapter#19]
I build the adapter x64. The build was successful but I get this error when I try to run it. 
I checked out the latest master.
![asio error](https://cloud.githubusercontent.com/assets/313363/7363326/2da1bfa2-ed96-11e4-8f25-16dd44d96172.PNG)

**Comment by andysterland** [comment]
Do you have another instance of IEDiagadapter.exe running? Or another app (like chrome) using port 9222?

**Comment by praveenpuglia** [comment]
I didn't have anything else running but somehow it didn't work. I restarted the system and it stopped throwing that error. Assuming some ghost process.
Now I get this... **Debug Assertion Failed** 
![image](https://cloud.githubusercontent.com/assets/313363/7370847/7e65a450-edda-11e4-8bbd-0ad6ed3d5649.png)

**Comment by alexcope** [comment]
This looks like it might be related to issue #9, which I'm working on currently
