### ISSUE TITLE
Refresh page / source debugging dysfunctional (vbox Win7 IE11)

### ISSUE THREAD

**Issue by obimod** [Microsoft/IEDiagnosticsAdapter#20]
1. Use Win7 IE11 virtual box retrievable via modern.ie
2. Download and execute IEDiagnosticsAdapter w/ the dll file, both on Desktop
3. Open internet explorer and navigate to a LAN website (via port 8383) to test
4. Open localhost:9222 in chrome, select the appropriate IE box, and click on the "Sources" tab
5. Set some break points in a particular JS file
6. Reload the IE page 

Expected result:
-- functional debugging

Actual result:
-- the connection is broken btwn chrome debugger and IE after the refresh

This essentially is blocking the ability to debug source code in IE using chrome debugger in VirtualBox. The LAN website is on the host machine (the one running VBox).

**Comment by obimod** [comment]
some console output...

[2015-04-28 17:08:55] [error] handle_read_frame error: websocketpp.transport:7 (
End of File)
Connection rejected for: /devtools/page/32A9EFB0-74C3-4722-B804-35C57CED70BC
[2015-04-28 17:10:08] [error] Handshake ended with HTTP error: 400
Client connection accepted for: /devtools/page/C35B8417-6D4F-4DB6-A9EA-1E85B57F0
1D7 as: 00060320

**Comment by obimod** [comment]
Perhaps it's something doing with an IP-address based URL?

**Comment by praveenpuglia** [comment]
is your VM running Windows 7 x64? I had those exact same set of errors here -  #9  Using the x86 version of IEDiagnosticsAdapter is the solution for now.

**Comment by obimod** [comment]
32-bit w/ Intel(R) Core i7-3615QM CPU @ 2.30GHz
dished out 512MB RAM to the VM

I think the frame error is also disconcerting.

**Comment by alexcope** [comment]
Thank you for the bug report. I'm currently working on a fix to issue #9, once I resolve that I'll look into this.

**Comment by alexcope** [comment]
This should be fixed with commit 47cfdf9ed5611ff46518ef76965393d608411dd9
