### ISSUE TITLE
Can't build with VS2013 Express

### ISSUE THREAD

**Issue by datoda** [Microsoft/IEDiagnosticsAdapter#23]
I downloaded the source zip for v0.1.4, and tried to build it with VS2013 Express on my Win 8.1. Alas, I can't seem to get the IEWebkitImpl project to be recognized-- In the solution explorer, IEWebkitImpl is marked as "Imcomplete", and "This project is incompatible with the current version of visual studio". 

My question-- Should VS2013 Express work with the project? Thanks.

**Comment by praveenpuglia** [comment]
I don't think it's going to work with express edition. You can try out the community 2013 edition. That should work.

**Comment by datoda** [comment]
Thanks, praveenpuglia. Using VS 2013 Community does work!
