### ISSUE TITLE
How to debug proxy.dll?

### ISSUE THREAD

**Issue by datoda** [Microsoft/IEDiagnosticsAdapter#24]
I am trying to debug the code in the Proxy and DebuggerCore project to no avail.

Here's some extra information: I am able to build and run/debug IEDiagnosticsAdpator (I will call it IEDA from here on). However, it appears that it's ieproxy.dll (by inspecting the IEDA process in procexp) that gets loaded as opposed to proxy.dll (or perhaps ieproxy.dll loads proxy.dll in turn?). Anyway, proxy.dll doesn't show up in the list of files/handles opened by IEDA procexp, and the breakpoints I set in Proxy and DebuggerCore are never materialized (they are shown with hollow circles as opposed to solid red dots). 

Am I missing something? Any insight would be appreciated.

**Comment by alexcope** [comment]
Proxy.dll get's injected into the tab that you are debugging. If you only have a single tab open and you try to attach to a process in visual studio you should see two instances of iexplore.exe, one with a name and one with no name. The named one is the internet Explorer frame, and the unnamed one is the tab. If you attach your debugger to the tab process and use the adapter to connect the chrome dev tools to that tab, you should be able to debug the JavaScript from Proxy.dll.

**Comment by datoda** [comment]
Thanks for the tip, alexcope. Two follow-up questions:
1. I think I can debug the js scripts injected in the browser thread this way. Is there a way to debug the debugger.js that's injected into the debugger thread?
2. It seems to me that once I hit a breakpoint in the cpp code in Proxy or DebuggerCore, then I can no longer debug js scripts. Is there a way to get around that?
Thanks again for your pointers.

**Comment by alexcope** [comment]
1) There should be two script engines injected onto the page. One with debugger.js and one with most of the rest of the scripts. You should be able to debug both the same way.

2) That seems strange, I've never seen that issue. On Monday I'll try to see if I can figure out what is going on with that.

**Comment by alexcope** [comment]
I think Visual Studio can't debug native and script code at the same time, which may be why you are seeing that issue. If it's blocking some work I can look into it more, but otherwise I'm not going to worry about it.
