### ISSUE TITLE
HTTP: Implement /json/version

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/IEDiagnosticsAdapter#35]
Chrome and other compliant debugging-servers is in addition to the WebSocket-endpoint, also exposing a HTTP endpoint where it's possible to get a JSON description of the current target.

Chrome also has a ```/json/version``` endpoint, which reveals information about the user agent/runtime. This could be useful for clients connecting to the adaptor.

**ANY /json/version**
*Note: This endpoint works using any HTTP method to be compatible with Chrome.*

```json
{
  Browser: "Chrome/37.0.2062.124",
  Protocol-Version: "1.1",
  User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36",
  WebKit-Version: "537.36 (@181352)"
}
```

**Comment by andysterland** [comment]
Should be simple to do. I just took a quick stab at it over in the add-JsonVersion branch just need to figure out some fun linker errors - yay.

**Comment by auchenberg** [comment]
My C++ isn't the best, but it looks quite good to me :)

https://github.com/Microsoft/IEDiagnosticsAdapter/compare/add-JsonVersion
