### ISSUE TITLE
DevTools refresh results in HTTP 400

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/IEDiagnosticsAdapter#40]
When connecting to the adaptor and refreshing the DevTools front-end the WebSocket connection is being reset, which doesn't seem to be handled by the adaptor.

![parallels desktop-1](https://cloud.githubusercontent.com/assets/173559/8426853/e25705a4-1f4d-11e5-8c26-acf30f742199.jpg)

**Comment by alexcope** [comment]
Fixed with commit  752be8230df0cbec8e89edc555b9fe21334fd584
