### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/IEDiagnosticsAdapter#49]
Last commit is months ago. Is this project dead or was development simply shifted to Edge core?

**Comment by andysterland** [comment]
Right now we're not actively working on this as we believe that the best place for a common API is in the browser itself and this project is a stepping stone for that. This project is always going to be useful for older versions of IE which are no longer being updated. If you do have any suggestions/issues/ideas for the project especially with regards to what scenarios you'd like to, or are, using it for we'd love to hear them.

Specifically, for Edge we don’t have any plans to announce for when, indeed we might first update this project to fully support Edge as a first step so we can experiment with connecting Edge with different tools without having to rev Edge.

**Comment by ckuetbach** [comment]
This is an absolute helpful tool for creating hybrid application.

I use this tool to debug a application running within MS Word (TaskPaneApp), IBM Notes (Webview) and even Outlook. The application itself is something like a cordova hybrid running in different windows applications.

Even if Edge will bring this features itself, will the embedded Webview of Word edge-enabled?

**Comment by andysterland** [comment]
Ah got ya. For what it's worth you do have other options you can make use of now;
If you're on Win10:

1. On Windows 10 you can use F12Chooser.exe in System32\F12\F12Chooser.exe and that will connect to any instance of Edge/IE running in the browser or an app.
2. Visual Studio from VS 2013 onwards can connect to any IE/Edge instance via the attach to process menu and selecting a debug type of "Script". VS also includes the DOM Explorer and Console from F12 so you can make use of those. 

Happy to help you get started with the tools if you'd like. It would be great to know if they are useful in your scenario.

**Comment by ckuetbach** [comment]
Yes, especially the F12Chooser is really helpful. It would be great, if these tools would be also available for other Windows Versions. A lot of our customers didn't update their OS yet.
