### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Niek** [Microsoft/IEDiagnosticsAdapter#54]
The last commit was almost 2 years ago, and the adapter hasn't been updated to the latest stable version of the Remote Debugging protocol (1.3). Does Microsoft intend to update this adapter in the (near) future?

**Comment by chrisfw** [comment]
Apparently yes due to [focus on Edge going forward](https://blogs.windows.com/msedgedev/2016/04/27/introducing-edge-diagnostics-adapter/).  
That said, there hasn't been any commit activity on the Edge adapter since December.
