### ISSUE TITLE
Getting error 400 and an empty Chrome Dev Tools

### ISSUE THREAD

**Issue by praveenpuglia** [Microsoft/IEDiagnosticsAdapter#9]
I tried the following steps and couldnt get it to work.

1. Load a page in IE11.
2. Run **IEDiagnosticsAdapter.exe** - Tried as administrator too.
3. Go to Chrome and hit `localhost:9222`
4. Select the page I want to inspect.

I get dev tools with everything being empty.

In console, I get this.
![adapter](https://cloud.githubusercontent.com/assets/313363/6979094/d6811a0e-d9fb-11e4-8c8a-b8465ba9d106.JPG)

**Comment by alexcope** [comment]
Try the following:
Under Internet options/advanced in Internet Explorer, ensure both "enable enhanced protective mode", and "enable 64 bit tabs for enhanced protective mode" are not checked. Then try using the 32 bit release.

**Comment by ionutvmi** [comment]
using the 32bit release seems to fix it for me

**Comment by praveenpuglia** [comment]
I had those checked off.  Using 32 bit resolved the issue. What's going on with the 64 bit ?

**Comment by praveenpuglia** [comment]
Closing this issue since x86 worked but a bug for x64 remains. Wondering if I should create a new issue for it.

**Comment by ionutvmi** [comment]
I do think we should keep it open since it will be fixed on x64 also.

**Comment by praveenpuglia** [comment]
yup... better than creating a new issue for x64. agreed. reopening.

**Comment by havenchyk** [comment]
It's not working for me even with x86 version. Same error as in the first comment. Is there another workaround?

**Comment by danmosemsft** [comment]
Is this on Windows 7 only?

I see this also produces the maxed CPU (eg., 50% CPU with 2 cores). 

Alex will debug both issues when he returns on Monday.

**Comment by JokerQyou** [comment]
For those who is getting 400 error on Window 7, it's important to have `Proxy.dll` placed within the folder where your `IEDiagnosticsAdapter.exe` locates. I was getting 400 error at first, and after downloading and placing `Proxy.dll` there it was gone. 
I would suggest releasing these files in a single ZIP file.

**Comment by Shazypro** [comment]
@praveenpuglia What fixed it for me was moving the `IEDiagnosticsAdapter.exe` to somewhere other than the initial/default "*Downloads*" folder. No `Proxy.dll` needed (Windows 8.1).

**Comment by praveenpuglia** [comment]
mine is on windows 7 and the downloaded files are on desktop.

**Comment by alexcope** [comment]
The x86 version should work if Proxy.dll and IEDiagnosticsAdapter.exe are in the same folder on the desktop, and "enable enhanced protective mode" is disabled in IE options. I would be very surprised if it somehow worked without Proxy.dll. I have not yet tested what happens if they are in a folder with lower permissions, but eventually we should have an installer which will get rid of that problem. Additionally I have verified the issue with the x64 release not working on 64 bit Windows 7, and will be looking into fixing it early next week.

**Comment by praveenpuglia** [comment]
awesome! sounds good! can you verify one thing if this requires elevated permissions to work properly on x64? I haven't tried it.

**Comment by alexcope** [comment]
This should be resolved with commit c910946
